//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Game/Scripts/Inputs/General/Hotkeys.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Game.Scripts.Inputs
{
    public partial class @MyControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @MyControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Hotkeys"",
    ""maps"": [
        {
            ""name"": ""Units"",
            ""id"": ""c8f01a8b-a740-4560-a0fb-2a2a5f497f24"",
            ""actions"": [
                {
                    ""name"": ""Selection"",
                    ""type"": ""Button"",
                    ""id"": ""fcca44b1-ce09-492d-ade5-31d01edc2f64"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OrderToMove"",
                    ""type"": ""Button"",
                    ""id"": ""4df5b146-9e63-4ec4-b2d9-038f82495d7c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ed170446-0831-4aa2-bf2b-fb210abd9070"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""067a9222-8c37-4e18-9d20-ab109bdda3ee"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OrderToMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Default"",
            ""bindingGroup"": ""Default"",
            ""devices"": []
        }
    ]
}");
            // Units
            m_Units = asset.FindActionMap("Units", throwIfNotFound: true);
            m_Units_Selection = m_Units.FindAction("Selection", throwIfNotFound: true);
            m_Units_OrderToMove = m_Units.FindAction("OrderToMove", throwIfNotFound: true);
        }

        ~@MyControls()
        {
            UnityEngine.Debug.Assert(!m_Units.enabled, "This will cause a leak and performance issues, MyControls.Units.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Units
        private readonly InputActionMap m_Units;
        private List<IUnitsActions> m_UnitsActionsCallbackInterfaces = new List<IUnitsActions>();
        private readonly InputAction m_Units_Selection;
        private readonly InputAction m_Units_OrderToMove;
        public struct UnitsActions
        {
            private @MyControls m_Wrapper;
            public UnitsActions(@MyControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Selection => m_Wrapper.m_Units_Selection;
            public InputAction @OrderToMove => m_Wrapper.m_Units_OrderToMove;
            public InputActionMap Get() { return m_Wrapper.m_Units; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UnitsActions set) { return set.Get(); }
            public void AddCallbacks(IUnitsActions instance)
            {
                if (instance == null || m_Wrapper.m_UnitsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UnitsActionsCallbackInterfaces.Add(instance);
                @Selection.started += instance.OnSelection;
                @Selection.performed += instance.OnSelection;
                @Selection.canceled += instance.OnSelection;
                @OrderToMove.started += instance.OnOrderToMove;
                @OrderToMove.performed += instance.OnOrderToMove;
                @OrderToMove.canceled += instance.OnOrderToMove;
            }

            private void UnregisterCallbacks(IUnitsActions instance)
            {
                @Selection.started -= instance.OnSelection;
                @Selection.performed -= instance.OnSelection;
                @Selection.canceled -= instance.OnSelection;
                @OrderToMove.started -= instance.OnOrderToMove;
                @OrderToMove.performed -= instance.OnOrderToMove;
                @OrderToMove.canceled -= instance.OnOrderToMove;
            }

            public void RemoveCallbacks(IUnitsActions instance)
            {
                if (m_Wrapper.m_UnitsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUnitsActions instance)
            {
                foreach (var item in m_Wrapper.m_UnitsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UnitsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UnitsActions @Units => new UnitsActions(this);
        private int m_DefaultSchemeIndex = -1;
        public InputControlScheme DefaultScheme
        {
            get
            {
                if (m_DefaultSchemeIndex == -1) m_DefaultSchemeIndex = asset.FindControlSchemeIndex("Default");
                return asset.controlSchemes[m_DefaultSchemeIndex];
            }
        }
        public interface IUnitsActions
        {
            void OnSelection(InputAction.CallbackContext context);
            void OnOrderToMove(InputAction.CallbackContext context);
        }
    }
}
